# PIPELINE DEFINITION
# Name: pod-placement-training-pipeline
# Description: Random Forest Training Pipeline
components:
  comp-evaluate-model:
    executorLabel: exec-evaluate-model
    inputDefinitions:
      artifacts:
        model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
        scenario_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        x_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        metrics:
          artifactType:
            schemaTitle: system.Metrics
            schemaVersion: 0.0.1
  comp-load-dataset:
    executorLabel: exec-load-dataset
    outputDefinitions:
      artifacts:
        dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-preprocess:
    executorLabel: exec-preprocess
    inputDefinitions:
      artifacts:
        dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        scenario_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        x_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        x_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-train-model:
    executorLabel: exec-train-model
    inputDefinitions:
      artifacts:
        x_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
  comp-upload-model:
    executorLabel: exec-upload-model
    inputDefinitions:
      artifacts:
        model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-evaluate-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - evaluate_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.4'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef evaluate_model(\n    model: Input[Model],\n    x_test: Input[Dataset],\n\
          \    y_test: Input[Dataset],\n    scenario_test: Input[Dataset],\n    metrics:\
          \ Output[Metrics],\n):\n    import joblib\n    import pandas as pd\n   \
          \ from sklearn.metrics import mean_squared_error\n\n    print(\"=\" * 60)\n\
          \    print(\"Loading model\")\n    print(\"=\" * 60)\n\n    rf = joblib.load(model.path)\n\
          \n    print(\"=\" * 60)\n    print(\"Loading test dataset\")\n    print(\"\
          =\" * 60)\n\n    X_test = pd.read_csv(x_test.path)\n    y_test_df = pd.read_csv(y_test.path)\n\
          \    scenario_df = pd.read_csv(scenario_test.path)\n\n    y_test = y_test_df[\"\
          score\"]\n    scenario_ids = scenario_df[\"scenario_id\"]\n\n    print(f\"\
          Testing Samples : {len(X_test)}\")\n\n    print(\"=\" * 60)\n    print(\"\
          Generating Predictions\")\n    print(\"=\" * 60)\n\n    predictions = rf.predict(X_test)\n\
          \n    print(\"=\" * 60)\n    print(\"Calculating RMSE\")\n    print(\"=\"\
          \ * 60)\n\n    rmse = mean_squared_error(\n        y_test,\n        predictions\n\
          \    ) ** 0.5\n\n    results_df = pd.DataFrame({\n        \"scenario_id\"\
          : scenario_ids,\n        \"true_score\": y_test,\n        \"predicted_score\"\
          : predictions,\n    })\n\n    print(\"=\" * 60)\n    print(\"Calculating\
          \ Top-1 Agreement\")\n    print(\"=\" * 60)\n\n    true_best = (\n     \
          \   results_df\n        .groupby(\"scenario_id\")[\"true_score\"]\n    \
          \    .idxmin()\n    )\n\n    pred_best = (\n        results_df\n       \
          \ .groupby(\"scenario_id\")[\"predicted_score\"]\n        .idxmin()\n  \
          \  )\n\n    true_best_rows = results_df.loc[true_best]\n    pred_best_rows\
          \ = results_df.loc[pred_best]\n\n    matches = 0\n\n    for scenario_id\
          \ in true_best_rows[\"scenario_id\"]:\n\n        true_index = true_best_rows[\n\
          \            true_best_rows[\"scenario_id\"] == scenario_id\n        ].index[0]\n\
          \n        pred_index = pred_best_rows[\n            pred_best_rows[\"scenario_id\"\
          ] == scenario_id\n        ].index[0]\n\n        if true_index == pred_index:\n\
          \            matches += 1\n\n    top1_agreement = matches / len(true_best_rows)\n\
          \n    print(\"=\" * 60)\n    print(\"Evaluation Results\")\n    print(\"\
          =\" * 60)\n\n    print(f\"RMSE            : {rmse:.4f}\")\n    print(f\"\
          Top-1 Agreement : {top1_agreement:.4f}\")\n\n    metrics.log_metric(\"RMSE\"\
          , float(rmse))\n    metrics.log_metric(\"Top1_Agreement\", float(top1_agreement))\n\
          \n    print(\"=\" * 60)\n    print(\"Metrics logged successfully\")\n  \
          \  print(\"=\" * 60)\n\n"
        image: pod-placement-trainer:v11
    exec-load-dataset:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - load_dataset
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.4'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef load_dataset(\n    dataset: Output[Dataset]\n):\n    from minio\
          \ import Minio\n    import os\n\n    print(\"=\" * 60)\n    print(\"Loading\
          \ dataset from MinIO\")\n    print(\"=\" * 60)\n\n    client = Minio(\n\
          \        \"host.minikube.internal:9000\",\n        access_key=\"minioadmin\"\
          ,\n        secret_key=\"minioadmin\",\n        secure=False,\n    )\n\n\
          \    os.makedirs(os.path.dirname(dataset.path), exist_ok=True)\n\n    client.fget_object(\n\
          \        bucket_name=\"datasets\",\n        object_name=\"dataset.csv\"\
          ,\n        file_path=dataset.path,\n    )\n\n    print(f\"Dataset saved\
          \ to: {dataset.path}\")\n\n"
        image: pod-placement-trainer:v11
    exec-preprocess:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - preprocess
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.4'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef preprocess(\n    dataset: Input[Dataset],\n    x_train: Output[Dataset],\n\
          \    x_test: Output[Dataset],\n    y_train: Output[Dataset],\n    y_test:\
          \ Output[Dataset],\n    scenario_test: Output[Dataset],\n):\n    import\
          \ pandas as pd\n    from sklearn.model_selection import train_test_split\n\
          \n    print(\"=\" * 60)\n    print(\"Loading dataset\")\n    print(\"=\"\
          \ * 60)\n\n    df = pd.read_csv(dataset.path)\n\n    print(f\"Dataset Shape\
          \ : {df.shape}\")\n\n    print(\"=\" * 60)\n    print(\"Encoding categorical\
          \ features\")\n    print(\"=\" * 60)\n\n    difficulty_mapping = {\n   \
          \     \"easy\": 0,\n        \"medium\": 1,\n        \"hard\": 2,\n    }\n\
          \n    df[\"difficulty\"] = df[\"difficulty\"].map(difficulty_mapping)\n\n\
          \    features = [\n        \"difficulty\",\n        \"cu_cpu_free_ratio\"\
          ,\n        \"du_cpu_free_ratio\",\n        \"cu_mem_free_ratio\",\n    \
          \    \"du_mem_free_ratio\",\n        \"latency_ms\",\n        \"latency_budget\"\
          ,\n        \"same_node\",\n        \"same_zone\",\n        \"cu_load\",\n\
          \        \"du_load\",\n        \"cu_cpu_violation\",\n        \"cu_mem_violation\"\
          ,\n        \"du_cpu_violation\",\n        \"du_mem_violation\",\n      \
          \  \"cpu_balance\",\n        \"mem_balance\",\n        \"cu_cpu_req\",\n\
          \        \"du_cpu_req\",\n        \"cu_mem_req\",\n        \"du_mem_req\"\
          ,\n    ]\n\n    X = df[features]\n    y = df[\"score\"]\n    scenario_ids\
          \ = df[\"scenario_id\"]\n\n    (\n        X_train,\n        X_test,\n  \
          \      y_train_df,\n        y_test_df,\n        _,\n        scenario_test_df,\n\
          \    ) = train_test_split(\n        X,\n        y,\n        scenario_ids,\n\
          \        test_size=0.2,\n        random_state=42,\n    )\n\n    print(\"\
          =\" * 60)\n    print(\"Saving processed datasets\")\n    print(\"=\" * 60)\n\
          \n    X_train.to_csv(x_train.path, index=False)\n\n    X_test.to_csv(x_test.path,\
          \ index=False)\n\n    y_train_df.to_frame(\"score\").to_csv(\n        y_train.path,\n\
          \        index=False,\n    )\n\n    y_test_df.to_frame(\"score\").to_csv(\n\
          \        y_test.path,\n        index=False,\n    )\n\n    scenario_test_df.to_frame(\"\
          scenario_id\").to_csv(\n        scenario_test.path,\n        index=False,\n\
          \    )\n\n    print(\"Preprocessing Completed\")\n\n    print(f\"Training\
          \ Samples : {len(X_train)}\")\n    print(f\"Testing Samples  : {len(X_test)}\"\
          )\n\n"
        image: pod-placement-trainer:v11
    exec-train-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.4'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_model(\n    x_train: Input[Dataset],\n    y_train: Input[Dataset],\n\
          \    model: Output[Model],\n):\n    import joblib\n    import pandas as\
          \ pd\n    from sklearn.ensemble import RandomForestRegressor\n\n    print(\"\
          =\" * 60)\n    print(\"Loading training data\")\n    print(\"=\" * 60)\n\
          \n    X_train = pd.read_csv(x_train.path)\n    y_train = pd.read_csv(y_train.path)[\"\
          score\"]\n\n    print(f\"Training Samples : {len(X_train)}\")\n    print(f\"\
          Number of Features : {X_train.shape[1]}\")\n\n    print(\"=\" * 60)\n  \
          \  print(\"Initializing Random Forest\")\n    print(\"=\" * 60)\n\n    rf\
          \ = RandomForestRegressor(\n        n_estimators=60,\n        max_depth=12,\n\
          \        random_state=42,\n        n_jobs=-1,\n    )\n\n    print(\"=\"\
          \ * 60)\n    print(\"Training Model\")\n    print(\"=\" * 60)\n\n    rf.fit(X_train,\
          \ y_train)\n\n    print(\"=\" * 60)\n    print(\"Saving Model\")\n    print(\"\
          =\" * 60)\n\n    joblib.dump(\n        rf,\n        model.path,\n      \
          \  compress=3,\n    )\n\n    print(f\"Model saved at : {model.path}\")\n\
          \n    print(\"=\" * 60)\n    print(\"Training Completed\")\n    print(\"\
          =\" * 60)\n\n"
        image: pod-placement-trainer:v11
    exec-upload-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - upload_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.4'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef upload_model(\n    model: Input[Model],\n):\n    from minio import\
          \ Minio\n\n    print(\"=\" * 60)\n    print(\"Connecting to MinIO\")\n \
          \   print(\"=\" * 60)\n\n    client = Minio(\n        \"host.minikube.internal:9000\"\
          ,\n        access_key=\"minioadmin\",\n        secret_key=\"minioadmin\"\
          ,\n        secure=False,\n    )\n\n    bucket_name = \"models\"\n    object_name\
          \ = \"model.pkl\"\n\n    if not client.bucket_exists(bucket_name):\n   \
          \     client.make_bucket(bucket_name)\n        print(f\"Created bucket:\
          \ {bucket_name}\")\n\n    print(\"=\" * 60)\n    print(\"Uploading Model\"\
          )\n    print(\"=\" * 60)\n\n    client.fput_object(\n        bucket_name=bucket_name,\n\
          \        object_name=object_name,\n        file_path=model.path,\n    )\n\
          \n    print(\"=\" * 60)\n    print(\"Upload Completed\")\n    print(\"=\"\
          \ * 60)\n\n    print(f\"Bucket : {bucket_name}\")\n    print(f\"Object :\
          \ {object_name}\")\n\n"
        image: pod-placement-trainer:v11
pipelineInfo:
  description: Random Forest Training Pipeline
  name: pod-placement-training-pipeline
root:
  dag:
    tasks:
      evaluate-model:
        cachingOptions: {}
        componentRef:
          name: comp-evaluate-model
        dependentTasks:
        - preprocess
        - train-model
        inputs:
          artifacts:
            model:
              taskOutputArtifact:
                outputArtifactKey: model
                producerTask: train-model
            scenario_test:
              taskOutputArtifact:
                outputArtifactKey: scenario_test
                producerTask: preprocess
            x_test:
              taskOutputArtifact:
                outputArtifactKey: x_test
                producerTask: preprocess
            y_test:
              taskOutputArtifact:
                outputArtifactKey: y_test
                producerTask: preprocess
        taskInfo:
          name: evaluate-model
      load-dataset:
        cachingOptions: {}
        componentRef:
          name: comp-load-dataset
        taskInfo:
          name: load-dataset
      preprocess:
        cachingOptions: {}
        componentRef:
          name: comp-preprocess
        dependentTasks:
        - load-dataset
        inputs:
          artifacts:
            dataset:
              taskOutputArtifact:
                outputArtifactKey: dataset
                producerTask: load-dataset
        taskInfo:
          name: preprocess
      train-model:
        cachingOptions: {}
        componentRef:
          name: comp-train-model
        dependentTasks:
        - preprocess
        inputs:
          artifacts:
            x_train:
              taskOutputArtifact:
                outputArtifactKey: x_train
                producerTask: preprocess
            y_train:
              taskOutputArtifact:
                outputArtifactKey: y_train
                producerTask: preprocess
        taskInfo:
          name: train-model
      upload-model:
        cachingOptions: {}
        componentRef:
          name: comp-upload-model
        dependentTasks:
        - evaluate-model
        - train-model
        inputs:
          artifacts:
            model:
              taskOutputArtifact:
                outputArtifactKey: model
                producerTask: train-model
        taskInfo:
          name: upload-model
schemaVersion: 2.1.0
sdkVersion: kfp-2.14.4
